name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create Artifacts
      run: cargo build --release --examples --verbose
    - name: Create Archive
      run: |
        $RUST_TOOLCHAIN = $(rustup show active-toolchain) -Split '[ -]'
        $RUST_ARCH=$RUST_TOOLCHAIN[1]
        $RUST_PLAT=$RUST_TOOLCHAIN[2]
        $RUST_OS=$RUST_TOOLCHAIN[3]
        $RUST_ENV=$RUST_TOOLCHAIN[4]
        $RUST_TARGET="${RUST_ARCH}-${RUST_PLAT}-${RUST_OS}-${RUST_ENV}"
        Compress-Archive -Path 'target\release\examples\capture-as-image.exe' -DestinationPath "capture-as-image-${RUST_TARGET}.zip"
        Write-Output "RUST_TARGET=$RUST_TARGET" >> $env:GITHUB_ENV
        Write-Output "ARTIFACT_PATH=capture-as-image-${RUST_TARGET}.zip" >> $env:GITHUB_ENV
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: ${{ env.RUST_TARGET }}
        path: ${{ env.ARTIFACT_PATH }}
        retention-days: 1
